// Generated by gencpp from file phidgets_interface/SetOutputState.msg
// DO NOT EDIT!


#ifndef PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATE_H
#define PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATE_H

#include <ros/service_traits.h>


#include <phidgets_interface/SetOutputStateRequest.h>
#include <phidgets_interface/SetOutputStateResponse.h>


namespace phidgets_interface
{

struct SetOutputState
{

typedef SetOutputStateRequest Request;
typedef SetOutputStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOutputState
} // namespace phidgets_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phidgets_interface::SetOutputState > {
  static const char* value()
  {
    return "fbfa7b3e79c838fbceaa8082ba51df74";
  }

  static const char* value(const ::phidgets_interface::SetOutputState&) { return value(); }
};

template<>
struct DataType< ::phidgets_interface::SetOutputState > {
  static const char* value()
  {
    return "phidgets_interface/SetOutputState";
  }

  static const char* value(const ::phidgets_interface::SetOutputState&) { return value(); }
};


// service_traits::MD5Sum< ::phidgets_interface::SetOutputStateRequest> should match 
// service_traits::MD5Sum< ::phidgets_interface::SetOutputState > 
template<>
struct MD5Sum< ::phidgets_interface::SetOutputStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets_interface::SetOutputState >::value();
  }
  static const char* value(const ::phidgets_interface::SetOutputStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets_interface::SetOutputStateRequest> should match 
// service_traits::DataType< ::phidgets_interface::SetOutputState > 
template<>
struct DataType< ::phidgets_interface::SetOutputStateRequest>
{
  static const char* value()
  {
    return DataType< ::phidgets_interface::SetOutputState >::value();
  }
  static const char* value(const ::phidgets_interface::SetOutputStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phidgets_interface::SetOutputStateResponse> should match 
// service_traits::MD5Sum< ::phidgets_interface::SetOutputState > 
template<>
struct MD5Sum< ::phidgets_interface::SetOutputStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets_interface::SetOutputState >::value();
  }
  static const char* value(const ::phidgets_interface::SetOutputStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets_interface::SetOutputStateResponse> should match 
// service_traits::DataType< ::phidgets_interface::SetOutputState > 
template<>
struct DataType< ::phidgets_interface::SetOutputStateResponse>
{
  static const char* value()
  {
    return DataType< ::phidgets_interface::SetOutputState >::value();
  }
  static const char* value(const ::phidgets_interface::SetOutputStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATE_H
