// Generated by gencpp from file phidgets_interface/SetOutputStateRequest.msg
// DO NOT EDIT!


#ifndef PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATEREQUEST_H
#define PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phidgets_interface
{
template <class ContainerAllocator>
struct SetOutputStateRequest_
{
  typedef SetOutputStateRequest_<ContainerAllocator> Type;

  SetOutputStateRequest_()
    : Index(0)
    , State(0)  {
    }
  SetOutputStateRequest_(const ContainerAllocator& _alloc)
    : Index(0)
    , State(0)  {
    }



   typedef int16_t _Index_type;
  _Index_type Index;

   typedef int16_t _State_type;
  _State_type State;




  typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOutputStateRequest_

typedef ::phidgets_interface::SetOutputStateRequest_<std::allocator<void> > SetOutputStateRequest;

typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateRequest > SetOutputStateRequestPtr;
typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateRequest const> SetOutputStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'phidgets_interface': ['/home/satellite/factorymonitor/src/phidgets_drivers/phidgets_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa04913c0effcdf73f06fbd9090a4e4a";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa04913c0effcdf7ULL;
  static const uint64_t static_value2 = 0x3f06fbd9090a4e4aULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets_interface/SetOutputStateRequest";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Index\n\
int16 State\n\
";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Index);
      stream.next(m.State);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetOutputStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets_interface::SetOutputStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "Index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Index);
    s << indent << "State: ";
    Printer<int16_t>::stream(s, indent + "  ", v.State);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATEREQUEST_H
