// Generated by gencpp from file phidgets_interface/SetOutputStateResponse.msg
// DO NOT EDIT!


#ifndef PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATERESPONSE_H
#define PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phidgets_interface
{
template <class ContainerAllocator>
struct SetOutputStateResponse_
{
  typedef SetOutputStateResponse_<ContainerAllocator> Type;

  SetOutputStateResponse_()
    : ret(0)  {
    }
  SetOutputStateResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
    }



   typedef int16_t _ret_type;
  _ret_type ret;




  typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetOutputStateResponse_

typedef ::phidgets_interface::SetOutputStateResponse_<std::allocator<void> > SetOutputStateResponse;

typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateResponse > SetOutputStateResponsePtr;
typedef boost::shared_ptr< ::phidgets_interface::SetOutputStateResponse const> SetOutputStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'phidgets_interface': ['/home/satellite/factorymonitor/src/phidgets_drivers/phidgets_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16207eaaf5c714348263d9afc66bbfea";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16207eaaf5c71434ULL;
  static const uint64_t static_value2 = 0x8263d9afc66bbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets_interface/SetOutputStateResponse";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ret\n\
\n\
";
  }

  static const char* value(const ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetOutputStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets_interface::SetOutputStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_INTERFACE_MESSAGE_SETOUTPUTSTATERESPONSE_H
